variables:
  pathToLogicAppProjectDirectory: '$(System.DefaultWorkingDirectory)/src/${{ variables.logicAppProjectDirectoryName }}'

trigger:
  branches:
      include:
          - provisioningservice
  paths:
      include:
          - src/MCOM.Provisioning.Functions/*
          - src/MCOM.Azure.Deployment/* 
          
pool:
  vmImage: 'windows-latest'

stages:
    - stage: CopyScripts
      displayName: Copy deployment scripts to artifact staging directory
      jobs:
          - job: CopyDS
            displayName: Copy deployment scripts to artifact staging directory
            steps:            
            - task: CopyFiles@2
              displayName: Copy deployment files
              inputs:
                SourceFolder: 'src/MCOM.Azure.Deployment'
                Contents: '**'
                TargetFolder: '$(Build.ArtifactStagingDirectory)'
            - publish: '$(Build.ArtifactStagingDirectory)'
              artifact: dropdeploymentscripts
    - stage: BuildArtifacts
      displayName: Build Artifacts
      condition: succeeded()
      jobs:
          - job: BuildAF
            displayName: Build azure functions
            steps:
            - task: UseDotNet@2
              displayName: Use Dot Net Core 6.0
              inputs:
                packageType: 'sdk'
                version: '6.0.x'
            - task: DotNetCoreCLI@2
              displayName: 'Restore project dependencies'
              inputs:
                command: 'restore'
                projects: 'src/**/*.csproj'
            - task: DotNetCoreCLI@2
              displayName: 'Publish the function project - $(BuildConfiguration)'
              inputs:
                command: 'publish'
                projects: 'src/MCOM.Provisioning.Functions/*.csproj'
                publishWebProjects: false
                arguments: '--no-build --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(BuildConfiguration)'
                zipAfterPublish: true
            - publish: '$(Build.ArtifactStagingDirectory)'
              artifact: dropazfunc
            - task: ArchiveFiles@2
              displayName: 'Create project zip for provisioning logic app'
              inputs:
                rootFolderOrFile: '$(pathToLogicAppProjectDirectory)'
                includeRootFolder: false
                archiveType: 'zip'
                archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
                replaceExistingArchive: true
            - publish: '$(Build.ArtifactStagingDirectory)'
              displayName: 'Publish logicapp artifact'
              artifact: droplogicapp
    - stage: RunTests
      displayName: Run Tests
      condition: succeeded()
      jobs:
          - job: RunTests
            displayName: Run Tests
            steps:
            - task: DotNetCoreCLI@2
              displayName: 'Run Unit tests'
              inputs:
                command: 'test'
                projects: 'src/MCOM.Tests/*.csproj'
                publishTestResults: true
                testRunTitle: 'MCOM Tests'
    - stage: DeployDev
      displayName: Deploy logic apps infrastructure and code to dev
      condition: succeeded()
      jobs:
          - deployment: DeployLogicApps
            displayName: Deploy MCOM Logic App            
            environment: 'dev'
            variables:
              deploymentMode: 'Incremental'
            strategy:
              runOnce:
                deploy:
                  steps:
                  - task: AzureCLI@2
                    displayName: 
                    inputs:
                      azureSubscription: '$(variables.AzureServiceConnectionName)'
                      scriptType: 'ps'
                      scriptLocation: 'scriptPath'
                      scriptPath: '${pipeline.workspace}/dropdeploymentscripts/deploy-mcom-provisioning-logicapps.ps1'
                      arguments: '-SubscriptionId $(variables.subscriptionId) -ResourceGroupName $(variables.resourceGroupName) -ResourceGroupLocation $(variables.resourceGroupLocation) -Environment $(variables.environment) -blobStorageUrl "https://stmcomarm$(variables.environment).blob.core.windows.net/armartifacts/armtemplates/"''           
                  - task: AzureFunctionApp@1
                    displayName: 'Deploy logic app workflows'
                    inputs:
                      azureSubscription: '$(variables.AzureServiceConnectionName)'
                      appType: 'functionApp'
                      appName: 'logic-mcom-provisioning-inttest'
                      package: '${Pipeline.Workspace}/droplogicapp/$(Build.BuildId).zip'
                      deploymentMethod: 'zipDeploy'

          